### ISSUE TITLE
background url() problems

### ISSUE THREAD

**Issue by neotropic2023** [sabberworm/PHP-CSS-Parser#102]
**body {background: #FFFFFF url("http://somesite.com/images/someimage.gif") repeat top center;}**

Becomes
**#fff url("http**

The : in http:// is breaking.

**Comment by sabberworm** [comment]
I can’t reproduce this problem. Maybe your string literal is incorrect? Can you show me some more code?

**Comment by neotropic2023** [comment]
`body {background: #989898 url("https://www.pets4you.com/newsite/pages/framework/bootstrap/images/backgrounds/transparent/custom_background_2.png") repeat top left;}`

When parsed, I get this as a returned value: **#989898 url("https** 

```
		if(file_exists($basepath.'styling.css')){
			$site_css = file_get_contents($basepath.'styling.css');
			require_once('bootstrap.php');
			$oParser = new Sabberworm\CSS\Parser($site_css);
			$oDoc = $oParser->parse();
			$selectors = $oDoc->getAllRuleSets();
			$nazwy = $oDoc->getContents();
			
			$settings = array();
			foreach($selectors as $selektor=>$val){       
				$w = $val->getSelectors(); 
				$label =  implode(', ', $w);
				$label = ($label == 'html, body') ? 'html,body':$label;  
				$settings[$label] = array();
				$tmp = $val->getRules();
				
				foreach($tmp as $nazwa => $attrib){
					$s = explode(":",$attrib);
					$settings[$label][$s[0]] = str_replace(";","",trim($s[1]));
				}         
			}
		}
```
I get everythign I need and everything is set, but backgroud URL's with "http:" or "https:" break.

Without either of those, I get:
`#989898 url("//www.pets4you.com/newsite/pages/framework/bootstrap/images/backgrounds/transparent/custom_background_2.png") repeat top left `

**Comment by neotropic2023** [comment]
My only work around is to remove http: when recreating the stylesheet. I just forgot to add https: to my changes. Which prompted me to remember this issue I posted, which I did forget about.
