### ISSUE TITLE
How to search for elements

### ISSUE THREAD

**Issue by ivanjaros** [sabberworm/PHP-CSS-Parser#118]
Hi,
I have a use case where I need to fetch all resources linked in the CSS(images, fonts, other css files).
I have briefly looked at the methods but I do not see any search methods.
Does this library support this or is it only for manual traversing of the CSS document as a whole?

**Comment by sabberworm** [comment]
You could use `getAllValues` on the Document to get all values used in the document and then iterate them to see if they are instances of `URL`…

**Comment by ivanjaros** [comment]
Sounds like simple regex for url() would be easier then.

**Comment by sabberworm** [comment]
Sure, you should choose the tools that best fit your needs.

**Comment by ivanjaros** [comment]
OK, thanks.
