### ISSUE TITLE
Replace rules lines by priority?

### ISSUE THREAD

**Issue by uitlaber** [sabberworm/PHP-CSS-Parser#126]
Need replace rules lines by priority its posible?
like:
Positioning
The block model
Typography
Decor
Animation
Miscellaneous

**Comment by sabberworm** [comment]
I’m not sure what you mean. Either way, this is not a support forum, it’s a bugtracker. If you have a specific problem where PHP-CSS-Parser does not work as expected, you can describe this precisely (in terms or what did happen vs. what you expected to happen) and reopen.
