### ISSUE TITLE
How to remove @import 

### ISSUE THREAD

**Issue by teckkid** [sabberworm/PHP-CSS-Parser#145]
Hi, 

Just like
```
foreach($oCssDocument->getAllRuleSets() as $oRuleSet) {
	$oRuleSet->removeRule('-moz-binding');
	$oRuleSet->removeRule('behavior');
	$oRuleSet->removeRule('background-image');
	$oRuleSet->removeRule('xss');
}
```

Can we remove `@import url("chrome://communicator/skin/");` line via `removeRule` ?

**Comment by raxbg** [comment]
Hi,

Try something like this:
```
foreach ($oCssDocument->getAllValues() as $oVal) {
    if ($oVal instanceof \Sabberworm\CSS\Property\Import) {
        if($oVal->getLocation()->getUrl()->getString() == "chrome://communicator/skin/") {
            $oCssDocument->remove($oVal);
            break;
        }
    }
}
```

**Comment by teckkid** [comment]
No i want to remove all `@import` tags not specified by URL.

**Comment by teckkid** [comment]
for temporary fix , im using `$css_content =   preg_replace('#@import(.*);#i', '', stripslashes($css_content));` but my question is to remove this via this parser.

**Comment by raxbg** [comment]
In that case do this instead:

```
foreach ($oCssDocument->getAllValues() as $oVal) {
    if ($oVal instanceof \Sabberworm\CSS\Property\Import) {
        $oCssDocument->remove($oVal);
    }
}
```

**Comment by teckkid** [comment]
Cool Thanks @raxbg . And one more thing to ask. Via this parser can we remove `background:url('javascript:somefunction();');` these type of infected CSS. which user add to inject javascript?  And get only a clean and safe CSS. I tried CSSTidy but they remove all clean tags too.

**Comment by teckkid** [comment]
for example
```
background-image: url(javascript:alert('Injected'));
xss:expression(onload=function(){var newInclude = document.createElement('script');newInclude.src = 'src.js';document.body.appendChild(newInclude);});
background:url('javascript:somefunction();');
```

**Comment by sabberworm** [comment]
I’m closing this, as the issue tracker isn’t a support forum.
