### ISSUE TITLE
unicode-range is not parsed

### ISSUE THREAD

**Issue by aruntvr** [sabberworm/PHP-CSS-Parser#158]
I try to parse this below mentioned font-face, unicode-range is missing in output..
**INPUT:**
`@font-face {
  font-family: 'specialCharacters';
  src: url('/fonts/some.otf') format('truetype');
  unicode-range: U+26;
  font-weight: normal;
  font-style: normal;
}`

**OUTPUT:**
`@font-face {font-family: "specialCharacters";src: url("/fonts/some.otf") format("truetype");font-weight: normal;font-style: normal;}`

Is there any solution for this ?

**Comment by sabberworm** [comment]
Did you try with the latest master? I just now merged #144.

**Comment by aruntvr** [comment]
Awesome, Now it's working..

**setCharset** and **getCharset** is getting error in parser.php because of **oParserHelper** is Undefined

**Comment by sabberworm** [comment]
> **setCharset** and **getCharset** is getting error in Parser.php because of **oParserHelper** is Undefined

Thanks for catching this I will fix it as soon as I can.

**Comment by sabberworm** [comment]
Thanks. Can you check again?

**Comment by aruntvr** [comment]
Thank you so much faster update... Cheers
