### ISSUE TITLE
Releasing 8.3.0

### ISSUE THREAD

**Issue by westonruter** [sabberworm/PHP-CSS-Parser#160]
Is there a list of issues/PRs that need to be closed for 8.3.0 to be released? It has been quite a few months since 8.2.0 was released. There are merged PRs currently in `master` that we'd like to include in a release of our project (https://github.com/ampproject/amp-wp/pull/1842) without maintaining a fork.

**Comment by sabberworm** [comment]
I think the current state of master is worthy of a release so I’ll do one shortly.
