### ISSUE TITLE
your documentation borders on incoherent...where are some specific examples?

### ISSUE THREAD

**Issue by menriquez** [sabberworm/PHP-CSS-Parser#172]
would it be too much to ask for some actual code samples that did something useful? 

not once in your documentation do you show how to just find and then modify a value.

its all just abstraction on abstraction..you seem to delight in making things more and more difficult to actually just use.

its a shame, because it seems like a very useful library.

you should get over yourself and realize there are always people smarter then you and people dumber then you.

**Comment by sabberworm** [comment]
I’m sorry you find the documentation hard to understand. I know the feeling of encountering exciting software only to be vexed by the high barrier to entry. I’m happy to acceptimprovements but honestly I don’t know where to start without some suggestions of what’s perplexing new users.
