### ISSUE TITLE
Discussion: Bump the minimal required PHP version?

### ISSUE THREAD

**Issue by oliverklee** [sabberworm/PHP-CSS-Parser#251]
Currently, this library's PHP version requirements align to those of the WordPress project (i.e., PHP >= 5.6 as a hard requirement according to https://wordpress.org/support/article/requirements/).

I've done some googling around and found contradicting information on when the PHP version requirements for WordPress will change, and which PHP version will then be required. @westonruter Do you have more (or official) information on this which you could share?

**Comment by westonruter** [comment]
There's an in-depth proposal for dropping support for old PHP versions via a fixed schedule: https://make.wordpress.org/core/2020/08/24/proposal-dropping-support-for-old-php-versions-via-a-fixed-schedule/

Matt Mullenweg's response to the proposal can be seen here: https://make.wordpress.org/core/2020/08/24/proposal-dropping-support-for-old-php-versions-via-a-fixed-schedule/#comment-39736

In short:

> The right policy for WordPress core is to have users drive what we support, measured by usage, not other projects with their own priorities and stakeholders.

It seems that once usage for PHP 5.x goes below 5% that this will then allow for WordPress to bump the minimum PHP requirement to PHP 7.

At the moment, PHP 5.6 accounts for 9.2% of WordPress installs: https://wordpress.org/about/stats/

![image](https://user-images.githubusercontent.com/134745/120691172-f87d6400-c45a-11eb-8302-772bd4bd0414.png)

Version	| Usage
--------|------
8.0 | 0.50%
7.4 | 30.80%
7.3 | 29.08%
7.2 | 16.42%
7.1 | 4.17%
7.0 | 5.53%
5.6 | 9.20%
5.5 | 0.96%
5.4 | 1.43%
5.3 | 1.35%
5.2 | 0.56%

So we're waiting on hosts to bump the PHP versions. 

There are 93 plugins in the WP directory that use PHP-CSS-Parser: https://wpdirectory.net/search/01F79GKCFAQRTSWMTQ07H7KVQS

I checked the ones with 20,000+ active installs and there's a split between the ones that require PHP 5 vs PHP 7:

Plugin | Requires PHP
-------|--------------
AMP | 5.6
Admin Menu Editor | 5.x
WooCommerce PDF Invoices & Packing Slips | 7.1
MailPoet – emails and newsletters in WordPress | 7.1
Advanced Contact form 7 DB | n/a
Jupiter X Core | 5.6
wpDataTables – Tables & Table Charts | 5.6
Ultimate FAQ – WordPress FAQ Plugin | n/a
WordPress Email Template Designer – WP HTML Mail | 7.2
Web Stories | 5.6 
WordPress Real Cookie Banner | 7.2
WooCommerce PDF Invoices, Packing Slips, Delivery Notes & Shipping Labels | 5.6

**Comment by oliverklee** [comment]
Done in #420. Closing.
