### ISSUE TITLE
Discussion: Hard-require the mbstring PHP extension?

### ISSUE THREAD

**Issue by oliverklee** [sabberworm/PHP-CSS-Parser#254]
To simplify things, could we hard-require the `mbstring` PHP extension via `composer.json` and deprecate the corresponding setting?

(This would be a breaking change, i.e., it would make sense to time this to happen just before the 9.0.0 release.)

@sabberworm @westonruter What do you think?

**Comment by westonruter** [comment]
We don't currently require the `mbstring` extension in the AMP plugin. [Also](https://www.php.net/manual/en/mbstring.installation.php):

> `mbstring` is a non-default extension. This means it is not enabled by default. You must explicitly enable the module with the `configure` option.

WordPress core does not require it, but it does [polyfill](https://github.com/WordPress/wordpress-develop/blob/a08bbbadd8d271dfa62cb72f0c72859a26439a96/src/wp-includes/compat.php#L43-L216) `mb_substr()` and `mb_strlen()`. Nevertheless, php-css-parser also uses `mb_strpos()` and `mb_strtolower()`, which are not polyfilled in WP.

So I don't think we can safely depend on it without breaking many sites.

**Comment by oliverklee** [comment]
@westonruter Thanks! Closing then.
