### ISSUE TITLE
Lacks PHP v8.1 compatibility

### ISSUE THREAD

**Issue by dleffler** [sabberworm/PHP-CSS-Parser#338]
PHP v8.1 (currently a release candidate) deprecates several parameter types and throws warnings such as Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in PHP-CSS-Parser\lib\Sabberworm\CSS\Parsing\ParserState.php on line 285

**Comment by oliverklee** [comment]
@dleffler We currently unfortunately cannot run the unit tests with PHP 8.1 yet. Would you be willing to list all problems you encounter with PHP 8.1? Then I can take a look. Thanks!

**Comment by xmav** [comment]
Hi @oliverklee !
Since this PR is merged can we expect new release?  (to used with pelago/emogrifier)

**Comment by sabberworm** [comment]
Yes, I’ll do a release shortly. I wasn’t sure whether @oliverklee was through with all the planned refactorings which I wanted to wait for before releasing but it seems like now is a good time.

**Comment by oliverklee** [comment]
No, I'm not through with my planned refactorings/cleanup/fixes. None of those should block a release, though. So please go ahead, @sabberworm! Thanks!

**Comment by xmav** [comment]
Hi @sabberworm! Do you have updates by any chance when new version will be released ?

**Comment by sabberworm** [comment]
@xmav version 8.4.0 is now out.
