### ISSUE TITLE
Add test mode setting

### ISSUE THREAD

**Issue by JakeQZ** [sabberworm/PHP-CSS-Parser#346]
It would be very useful if there was a way for exceptions caught internally to be propagated.

When unit-testing our own code we'd like to have any sign of an error fail the test in such a way that we can easily see why.  Or, in certain scenarios, we might want to deliberately throw an exception for a consumer running their own tests.

This would probably involve adding a flag to `Sabberworm\CSS\Settings` and checking it whenever an exception is caught internally, to rethrow accordingly (like we do [here](https://github.com/MyIntervals/emogrifier/blob/v6.0.0/src/CssInliner.php#L199-L203)).

For background, see https://github.com/MyIntervals/emogrifier/issues/1129.

**Comment by sabberworm** [comment]
IMHO, using `\Sabberworm\CSS\Settings::create()->beStrict()` shouldn’t swallow any exceptions. Is this what you need?

**Comment by JakeQZ** [comment]
> Is this what you need?

Yes, sorry, I misunderstood how that setting was supposed to work, and believed it would work in somewhat the opposite way to how it does.

I thought lenient would mean allow rules with invalid selectors and provide them in the parsed data.  Whereas in fact it means discard the rules nonetheless but carry trying to parse the remainder.

Happy to close unless you think the documentation could be clarified (I think "choke" is a bit unclear and could be more clearly written as "throw an exception" - I actually thought it implied a Heimlich manoeuvre would be carried out so the parser could carry on, but that it would cough up rather than digest the specific rule that caused the error).

**Comment by sabberworm** [comment]
> I actually thought it implied a Heimlich manoeuvre would be carried out so the parser could carry on, but that it would cough up rather than digest the specific rule that caused the error).

# 🤣

**Comment by sabberworm** [comment]
Thanks for the hint, I updated the readme as suggested.
