### ISSUE TITLE
[href=https://example.org] selector is discarded

### ISSUE THREAD

**Issue by JakeQZ** [sabberworm/PHP-CSS-Parser#347]
This is a BC issue following #162.

Maybe the regex can be fixed, or maye a different approach is needed.

**Comment by JakeQZ** [comment]
Note this is using the selector `[href=https://example.org]` as written.  AFAIK there is no requirement for the value to be quoted.

**Comment by JakeQZ** [comment]
Background and more detail at https://github.com/MyIntervals/emogrifier/issues/1129.

**Comment by raxbg** [comment]
Hi, you don't need the quotes on the HTML side but you seem to need them in CSS.

Please take a look at this pen https://codepen.io/raxbg/pen/OJZgRVz

**Comment by JakeQZ** [comment]
> Hi, you don't need the quotes on the HTML side but you seem to need them in CSS.

Looks like you are right (neither Chrome nor Firefox apply the CSS rule without quotes), and thus the test referred to in https://github.com/MyIntervals/emogrifier/issues/1129 was invalid.
