### ISSUE TITLE
GitHub releases page not up to date with tags (missing 8.4.0)

### ISSUE THREAD

**Issue by leonstafford** [sabberworm/PHP-CSS-Parser#364]
Please see https://github.com/sabberworm/PHP-CSS-Parser/releases/

8.4.0 was tagged December 2021, but not yet on GitHub releases page - not obvious there's an 8.4.0 when visiting repo's homepage.

Suggest to create release for 8.4.0

**Comment by oliverklee** [comment]
Done: https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/8.4.0

Thanks for noticing the missing release and letting us know! :pray:
