### ISSUE TITLE
Parsing time is sometimes extremely long

### ISSUE THREAD

**Issue by pietervogelaar** [sabberworm/PHP-CSS-Parser#84]
Hi,

Your CSS parser works great in a lot of situations, thanks! However, for certain stylesheets it takes extremely long before the parser is finished. Do you know why this URL takes so long to parse?

http://www.autorijschoolmw.nl/t3-assets/css/css-81e7e.css

Pieter

**Comment by mstduff** [comment]
disabling multibyte support seems to solve long parsing times, review docs on how to do that
