### ISSUE TITLE
Parse Exception for valid css

### ISSUE THREAD

**Issue by maraisr** [sabberworm/PHP-CSS-Parser#85]
This selector wont pass, and I get a Identifier expected. Got ":80em"

This is the selector
`@media(min-width:80em){a[href^=fax],a[href^=tel]{cursor:text;pointer-events:none}a[href^=fax]:hover,a[href^=tel]:hover{text-decoration:none}}`

**Comment by sabberworm** [comment]
Closing this as a duplicate of #75
