### ISSUE TITLE
How to get position of selectors

### ISSUE THREAD

**Issue by codeyash** [sabberworm/PHP-CSS-Parser#87]
Examples show how to get all selectors. I need position of selectors. I mean cursor position in file of that selector.

Is that possible or not supported yet?

**Comment by sabberworm** [comment]
No, I’m afraid that’s not currently possible. But I think it would be simple to implement: store the current value of `$this->iCurrentPosition` when creating the `DeclarationBlock` object.

**Comment by codeyash** [comment]
ok Thanks for info
