### ISSUE TITLE
Require? Include?

### ISSUE THREAD

**Issue by neotropic2023** [sabberworm/PHP-CSS-Parser#89]
To read a file, for example, you’d do the following:

REQUIRE('......................................'); <-- And what file do we call?

$oCssParser = new Sabberworm\CSS\Parser(file_get_contents('somefile.css'));
$oCssDocument = $oCssParser->parse();

**Comment by sabberworm** [comment]
If you installed with composer, you’ll want to `require 'vendor/autoload.php';` (see the [docs](https://getcomposer.org/doc/01-basic-usage.md#autoloading)).

**Comment by mikeytown2** [comment]
You can also use this as a simple psr-0 class loader

<?php
set_include_path('DIR_STRUCTURE' . '/PHP-CSS-Parser/lib/');
spl_autoload_register(function ($class) {
  $file = preg_replace('#\\\|_(?!.+\\\)#','/', $class) . '.php';
  if (stream_resolve_include_path($file)) {
    require $file;
  }
});
?>
