### ISSUE TITLE
Doesn't work in PHP 7 = Cannot use Sabberworm\CSS\Value\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by josenobile** [sabberworm/PHP-CSS-Parser#91]
I just tried PHP 7 (master) that is coming in about 4 months (October 2015).

Fatal error: Cannot use Sabberworm\CSS\Value\String as String because 'String' is a special class name in ..vendor/sabberworm/php-css-parser/lib/Sabberworm/CSS/Parser.php on line 20

More information here: http://php.net/manual/en/reserved.other-reserved-words.php

**Comment by sabberworm** [comment]
If only they had fixed case-sensitivity for class names then this would not be an issue…

Actually this class had been named CSSString before being refactored into namespaces. Oh well, I’ll revert that for the next major release…

**Comment by josenobile** [comment]
ok, thank you.

**Comment by sabberworm** [comment]
Version [7.0.0](https://github.com/sabberworm/PHP-CSS-Parser/releases/tag/7.0.0) fixes this.
