### ISSUE TITLE
Accessing Properties Individually

### ISSUE THREAD

**Issue by FrancisBaileyH** [sabberworm/PHP-CSS-Parser#92]
I need to store individual values as strings  (i.e. the $sSelector variable in the Selector class)  but I noticed property variables are all private. I looked through the documentation as well as the source code and there doesn't seem to be any facility/method to get them. 

So my question is if there is a proper way to access these properties or a recommendation (i.e. make the property variables public).

Thanks

**Comment by sabberworm** [comment]
Most properties have setters and getters. In your case, that’s `Sabberworm\CSS\Property\Selector::getSelector()` and `setSelector($sSelector)`.

If a setter or getter is missing, you can add it and send a pull-request, which I will then merge.
