### ISSUE TITLE
Please tag the latest master to 6.0.1

### ISSUE THREAD

**Issue by meenie** [sabberworm/PHP-CSS-Parser#95]
You currently have a bug fix for PHP 5.3.3 in master but not yet tagged.  Could you please create one quickly so I can update my library https://github.com/meenie/munee for the fix?

Thanks a ton!

**Comment by sabberworm** [comment]
Done.

**Comment by meenie** [comment]
@sabberworm Thanks a ton :).  It seems Packagist isn't pulling in your latest tag.  Can you click the "Update" button for the package after you login to Packagist?

**Comment by sabberworm** [comment]
Actually, I don’t own the package on packagist, it was @nicolopignatelli who created the composer package. But usually packagist updates their tags once a day.

**Comment by meenie** [comment]
@sabberworm Alright, no worries :).  Thanks again!
